In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
#vocabulary size
voc_size=10000

In [5]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[7622, 8746, 4253, 8400], [7622, 8746, 4253, 8764], [7622, 9476, 4253, 2737], [5544, 7453, 7404, 2590, 7009], [5544, 7453, 7404, 2590, 1747], [8751, 7622, 2852, 4253, 123], [7064, 7943, 6826, 2590]]


In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)


[[   0    0    0    0 7622 8746 4253 8400]
 [   0    0    0    0 7622 8746 4253 8764]
 [   0    0    0    0 7622 9476 4253 2737]
 [   0    0    0 5544 7453 7404 2590 7009]
 [   0    0    0 5544 7453 7404 2590 1747]
 [   0    0    0 8751 7622 2852 4253  123]
 [   0    0    0    0 7064 7943 6826 2590]]


In [9]:
dim=15

In [10]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [12]:
print(model.predict(embedded_docs))

[[[-0.04382737 -0.01033894  0.00975747 -0.02312381  0.0102576
   -0.02399296  0.03142769 -0.03459787  0.02250684 -0.03383654]
  [-0.04382737 -0.01033894  0.00975747 -0.02312381  0.0102576
   -0.02399296  0.03142769 -0.03459787  0.02250684 -0.03383654]
  [-0.04382737 -0.01033894  0.00975747 -0.02312381  0.0102576
   -0.02399296  0.03142769 -0.03459787  0.02250684 -0.03383654]
  [-0.04382737 -0.01033894  0.00975747 -0.02312381  0.0102576
   -0.02399296  0.03142769 -0.03459787  0.02250684 -0.03383654]
  [ 0.03007282 -0.00726711 -0.0213568  -0.04979506 -0.02537057
   -0.02668265 -0.0028493   0.00674192  0.02161883  0.02095585]
  [-0.01219127 -0.00078652  0.02449473 -0.04800015  0.03680228
   -0.02448188  0.04892888 -0.03713629  0.00756086 -0.04894929]
  [ 0.03218186  0.00636264  0.04161121 -0.03130794  0.04226508
    0.04466014 -0.01242491 -0.03268854  0.01074276  0.03706687]
  [ 0.01674613 -0.01889863 -0.00460637  0.0052284  -0.0048928
   -0.00124903 -0.03772733  0.00461848 -0.00754709 -0

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 7622, 8746, 4253, 8400], dtype=int32)

In [14]:
print(model.predict(embedded_docs[0]))

[[[-0.04382737 -0.01033894  0.00975747 -0.02312381  0.0102576
   -0.02399296  0.03142769 -0.03459787  0.02250684 -0.03383654]]

 [[-0.04382737 -0.01033894  0.00975747 -0.02312381  0.0102576
   -0.02399296  0.03142769 -0.03459787  0.02250684 -0.03383654]]

 [[-0.04382737 -0.01033894  0.00975747 -0.02312381  0.0102576
   -0.02399296  0.03142769 -0.03459787  0.02250684 -0.03383654]]

 [[-0.04382737 -0.01033894  0.00975747 -0.02312381  0.0102576
   -0.02399296  0.03142769 -0.03459787  0.02250684 -0.03383654]]

 [[ 0.03007282 -0.00726711 -0.0213568  -0.04979506 -0.02537057
   -0.02668265 -0.0028493   0.00674192  0.02161883  0.02095585]]

 [[-0.01219127 -0.00078652  0.02449473 -0.04800015  0.03680228
   -0.02448188  0.04892888 -0.03713629  0.00756086 -0.04894929]]

 [[ 0.03218186  0.00636264  0.04161121 -0.03130794  0.04226508
    0.04466014 -0.01242491 -0.03268854  0.01074276  0.03706687]]

 [[ 0.01674613 -0.01889863 -0.00460637  0.0052284  -0.0048928
   -0.00124903 -0.03772733  0.00461848 